DELETE FROM ACCESS_PROFILE WHERE ID_ACCESS_PROFILE = ?;
DELETE FROM ACCOUNT WHERE ID_ACCOUNT = ?;
DELETE FROM APP_PROFILE WHERE ID_PROFILE = ?;
DELETE FROM STUDENT WHERE ID_STUDENT = ?;
DELETE FROM SYSTEM_DASHBOARD WHERE ID_SYS_DASHBOARD = ?;
DELETE FROM TEACHER WHERE ID_TEACHER = ?;

