SELECT ID_ACCESS_PROFILE, ID_PROFILE, ID_SYS_DASHBOARD FROM ACCESS_PROFILE;
SELECT ID_ACCOUNT, NIC, ID_APP_PROFILE, PASSWORD, FIRST_NAME, LAST_NAME, LAST_NAME2, MAIL_APP, DISCHARGE_DATE, DATE_OF_LOW, APP_PROFILEID_PROFILE FROM ACCOUNT;
SELECT NAME, DESCRIPTION, ID_PROFILE FROM APP_PROFILE;
SELECT FIRST_NAME, LAST_NAME, LAST_NAME2, MAIL_CONTACT, SEX, WEIGHT, BIRTHDATE, DAY_OF_INCOME, DATE_OF_LOW, STATUS, CATEGORY, TELEPHONE_CONTACT, ADDRESS, DOC_ID, ID_STUDENT, ID_TEACHER FROM STUDENT;
SELECT ID_SYS_DASHBOARD, NAME, DESCRIPTION FROM SYSTEM_DASHBOARD;
SELECT FIRST_NAME, LAST_NAME, LAST_NAME2, CATEGORY, TELEPHONE_CONTACT, MAIL, DOC_ID, ID_TEACHER FROM TEACHER;

