SELECT COUNT(1)
FROM 
(SELECT 
IF((YEAR(NOW()) - YEAR(_LAST_PAID_MONTHY))=0,(IF((MONTH(NOW()) - MONTH(T._LAST_PAID_MONTHY) )<=3,'YES','NO')),'NO') AS ACTIVE
FROM STUDENT S ,(
SELECT D.ID_STUDENT,MAX(P.PAYDAY) AS _LAST_PAID_MONTHY 
FROM PAYMENTS P, DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE P.ID_PAYMENT = D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SUB_GROUP_DESCRIPTION ='CLASES'
GROUP BY D.ID_STUDENT
) T 
WHERE 
 (S.ID_STUDENT =T.ID_STUDENT )
 ) STATE_STUDENTS
 WHERE STATE_STUDENTS.STATUS ='ACTIVE'
 
 ;
 
 SELECT DATE_FORMAT(MAX(P.PAYDAY), '%d/%m/%Y') AS  LAST_PAID_MONTHY,MAX(P.PAYDAY) as _LAST_PAID_MONTHY,D.ID_STUDENT,MAX(P.PAYDAY) AS LAST_PAID_NO_FORMAT 
FROM PAYMENTS P, DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE P.ID_PAYMENT = D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SUB_GROUP_DESCRIPTION ='CLASES'
GROUP BY D.ID_STUDENT