/*INSERT INTO ACCESS_PROFILE(ID_ACCESS_PROFILE, ID_PROFILE, ID_SYS_DASHBOARD) VALUES (?, ?, ?);
INSERT INTO ACCOUNT(ID_ACCOUNT, NIC, ID_APP_PROFILE, PASSWORD, FIRST_NAME, LAST_NAME, LAST_NAME2, MAIL_APP, DISCHARGE_DATE, DATE_OF_LOW, APP_PROFILEID_PROFILE) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO APP_PROFILE(NAME, DESCRIPTION, ID_PROFILE) VALUES (?, ?, ?);
INSERT INTO STUDENT(FIRST_NAME, LAST_NAME, LAST_NAME2, MAIL_CONTACT, SEX, WEIGHT, BIRTHDATE, DAY_OF_INCOME, DATE_OF_LOW, STATUS, CATEGORY, TELEPHONE_CONTACT, ADDRESS, DOC_ID, ID_STUDENT, ID_TEACHER) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO SYSTEM_DASHBOARD(ID_SYS_DASHBOARD, NAME, DESCRIPTION) VALUES (?, ?, ?);
INSERT INTO TEACHER(FIRST_NAME, LAST_NAME, LAST_NAME2, CATEGORY, TELEPHONE_CONTACT, MAIL, DOC_ID, ID_TEACHER) VALUES (?, ?, ?, ?, ?, ?, ?, ?);*/
/** APP_PROFILE
*PAYMENTS
STUDENTS
TEACHERS
ADMINISTRATORS
CONSULTANT_AGENT
OPERATOR
**/
INSERT INTO APP_PROFILE(NAME, DESCRIPTION) VALUES ('OPERATOR','OPERADOR/SECRETARIA/EMPLEADO');
INSERT INTO APP_PROFILE(NAME, DESCRIPTION) VALUES ('STUDENTS', 'ESTUDIANTE - NO IMPLEMENTADO');
INSERT INTO APP_PROFILE(NAME, DESCRIPTION) VALUES ('TEACHERS', 'MAESTRO DENTRO DEL DOJO');
INSERT INTO APP_PROFILE(NAME, DESCRIPTION) VALUES ('ADMINISTRATORS', 'ADMINISTRADOR DE LA APP -TOTAL CONTROL');
INSERT INTO APP_PROFILE(NAME, DESCRIPTION) VALUES ('CONSULTANT_AGENT', 'AGENTE DE CONSULTA - COMMUNITY MANAGER');
COMMIT;
SELECT * FROM APP_PROFILE;
SELECT NOW() + 0;

SELECT DATE_FORMAT('2007-10-04 22:23:00', '%H:%i:%s');
SELECT DATE_FORMAT('2018-02-06 00:00:00', '%W %M %Y');
/**
ID_ACCOUNT	int(10)
NIC	varchar(20)
ID_APP_PROFILE	int(10)
PASSWORD	binary(255)
FIRST_NAME	varchar(40)
LAST_NAME	varchar(40)
LAST_NAME2	varchar(40)
MAIL_APP	varchar(40)
DISCHARGE_DATE	date
DATE_OF_LOW	date
APP_PROFILE_ID	int(10)
*/
SELECT * FROM APP_PROFILE;
START TRANSACTION;
INSERT INTO ACCOUNT(NIC,
 PASSWORD, 
 FIRST_NAME, 
 LAST_NAME,
 LAST_NAME2,
 EMAIL,
 DISCHARGE_DATE,
 DATE_OF_LOW,
 ID_APP_PROFILE) 
 VALUES ('LRO',
 '7110eda4d09e062aa5e4a390b0a572ac0d2c0220',
 'Lorenzo', 
 'Rodriguez',
 ' AQQ', 
 'lro.1971@yahoo.com',
 '2018-02-06 00:00:00',
 '2018-02-06 00:00:00',
 4);
 COMMIT;
INSERT INTO ACCOUNT(NIC,PASSWORD, FIRST_NAME, LAST_NAME, LAST_NAME2, MAIL_APP, DISCHARGE_DATE, DATE_OF_LOW, ID_APP_PROFILE) VALUES ('JVE','81fe8bfe87576c3ecb22426f8e57847382917acf', 'Jorge', ' ',' ' , ' ', '2018-02-06 00:00:00', '2999-12-31', 1);
INSERT INTO ACCOUNT(NIC,PASSWORD, FIRST_NAME, LAST_NAME, LAST_NAME2, MAIL_APP, DISCHARGE_DATE, DATE_OF_LOW, ID_APP_PROFILE) VALUES ('ADMIN','81fe8bfe87576c3ecb22426f8e57847382917acf', 'Admin', 'Admin',' ',' ', '2018-02-06 00:00:00', '2999-12-31', 4);
COMMIT;
SELECT * FROM ACCOUNT;
UPDATE ACCOUNT SET DATE_OF_LOW='2999-12-31' WHERE ID_ACCOUNT=1;
#######################################################################
## INSERT DE USUARIOS DE PRUEBA
INSERT INTO USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,ROLE,DATE_REGISTRATION) VALUES('lro.1971@yahoo.com','lro','lro','1234','ROLE_ADMIN','2018-02-11 00:00:00');
INSERT INTO USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,ROLE,DATE_REGISTRATION) VALUES('jvega@hotmail.com','jve','jve','$2a$10$pLij2JswyCheXlwaX6YjHeryOhOZPc/P93m4dHGfdK.VrMg1bAHpy','ROLE_USER','2018-02-16 00:00:00');

select * from user;
## INSERT DE CATALOGOS
## GENERO
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('GENDER001','MASCULINO','GENDER');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('GENDER002','FEMENINO','GENDER');
#CATEGORIA
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('CATEGORY01','CADETE','CATEGORY');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('CATEGORY02','JUVENIL','CATEGORY');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('CATEGORY03','INFANTIL','CATEGORY');
#OCUPACIONES
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1001','ABOGADO ','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1002','ADMINISTRADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1003','ADMINISTRATIVO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1004','AGRÓNOMO ','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1005','ALERGÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1006','ALERGISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1007','ALERGÓLOGA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1008','ALERGISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1009','ALMACENISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1010','ANATOMISTA ','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1011','ANESTESIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1012','ANESTESISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1013','ANESTESIÓLOGA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1014','ANESTESISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1015','ANTOLOGISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1016','ANTROPÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1017','ARABISTA ','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1018','ARCHIVERO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1019','ARQUEÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1020','ARQUITECTO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1021','ASESOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1022','ASTROFÍSICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1023','ASTRÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1024','ASTRÓNOMO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1025','ATLETA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1026','AUXILIAR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1027','AVICULTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1028','BACTERIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1029','BIBLIÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1030','BIBLIOTECARIO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1031','BIOFÍSICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1032','BIÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1033','BIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1034','BIOQUÍMICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1035','BOTÁNICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1036','CANCERÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1037','CARDIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1038','CARTÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1039','CATEDRÁTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1040','CIRUJANO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1041','CODIRECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1042','CONSERJE','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1043','COORDINADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1044','COSMÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1045','COSMÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1046','CRIMINALISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1047','DECANO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1048','DECORADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1049','DEMÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1050','DENTISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1051','DERMATÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1052','DIBUJANTE','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1053','DIRECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1054','DOCTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1055','ECÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1056','ECONOMISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1057','EDUCADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1058','ENDOCRINÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1059','ENFERMERO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1060','ENÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1061','ENTOMÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1062','EPIDEMIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1063','ESPELEÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1064','ESTADÍSTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1065','ETIMÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1066','ETIMOLOGISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1067','ETIMÓLOGA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1068','ETIMOLOGISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1069','ETNÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1070','ETNÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1071','FARMACÉUTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1072','FILÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1073','FILÓSOFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1074','FISCAL','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1075','FÍSICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1076','FISIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1077','FISIOTERAPEUTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1078','FONETISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1079','FONÍATRA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1080','FONÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1081','FORENSE','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1082','FOTÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1083','GEMÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1084','GENETISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1085','GEODESTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1086','GEOFÍSICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1087','GEÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1088','GEÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1089','GEOQUÍMICA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1090','GERENTE','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1091','GERIATRA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1092','TRABAJADOR SOCIAL','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1093','GRAFÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1094','GRAMÁTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1095','HEMATÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1096','HEPATÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1097','HIDROGEÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1098','HIDRÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1099','HIDRÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1100','HIGIENISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1101','HISPANISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1102','HISTORIADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1103','HOMEÓPATA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1104','INFORMÁTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1105','INGENIERO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1106','INGENIERO TÉCNICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1107','INMUNÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1108','INSPECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1109','JARDINERO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1110','JUEZ','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1111','LATINISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1112','LECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1113','LEXICÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1114','LEXICÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1115','LINGÜISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1116','LOGOPEDA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1117','MAESTRO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1118','MATEMÁTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1119','MATRÓN','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1120','MEDICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1121','METEORÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1122','MICÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1123','MICROBIOLÓGICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1124','MICROCIRUJANO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1125','MIMÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1126','MINERALOGISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1127','MONITOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1128','MUSICÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1129','NATURÓPATA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1130','NEFRÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1131','NEUMÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1132','NEUROANATOMISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1133','NEUROBIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1134','NEUROCIRUJANO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1135','NEUROEMBRIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1136','NEUROFISIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1137','NEURÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1138','NUTRÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1139','OCEANÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1140','ODONTÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1141','OFICIAL','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1142','OFICINISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1143','OFTALMÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1144','ONCÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1145','ÓPTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1146','OPTOMETRISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1147','ORDENANZA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1148','ORIENTADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1149','ORNITÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1150','ORTOPÉDICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1151','ORTOPEDISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1152','OSTEÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1153','OSTEÓPATA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1154','OTORRINOLARINGÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1155','PALEOBIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1156','PALEOBOTÁNICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1157','PALEÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1158','PALEÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1159','PALEONTÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1160','PATÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1161','PEDAGOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1162','PEDIATRA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1163','PEDICURO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1164','PERIODISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1165','PERITO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1166','INGENIERO TÉCNICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1167','PISCICULTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1168','PODÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1169','PORTERO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1170','PREHISTORIADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1171','PRESIDENTE','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1172','PROCTÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1173','PROFESOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1174','PROGRAMADOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1175','PROTÉSICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1176','PROVEEDOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1177','PSICOANALISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1178','PSICÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1179','PSICOFÍSICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1180','PSICOPEDAGOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1181','PSICOTERAPEUTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1182','PSIQUIATRA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1183','PUBLICISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1184','PUBLICITARIO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1185','PUERICULTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1186','QUÍMICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1187','QUIROPRÁCTICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1188','RADIOASTRÓNOMO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1189','RADIOFONISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1190','RADIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1191','RADIOTÉCNICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1192','RADIOTELEFONISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1193','RADIOTELEGRAFISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1194','RADIOTERAPEUTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1195','RECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1196','SANITARIO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1197','SECRETARIO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1198','SEXÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1199','SISMÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1200','SOCIÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1201','SUBDELEGADO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1202','SUBDIRECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1203','SUBSECRETARIO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1204','TÉCNICO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1205','TELEFONISTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1206','TEÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1207','TERAPEUTA','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1208','TOCOGINECÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1209','TOCÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1210','TOXICÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1211','TRADUCTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1212','TRANSCRIPTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1213','TRAUMATÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1214','TUTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1215','URÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1216','VETERINARIO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1217','VICEDECANO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1218','VICEDIRECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1219','VICEGERENTE','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1220','VICEPRESIDENTE','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1221','VICERRECTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1222','VICESECRETARIO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1223','VIRÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1224','VITICULTOR','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1225','VULCANÓLOGO ','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1226','XILÓGRAFO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1227','ZOÓLOGO','EMPLOYMENT');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('EMPLOY1228','ZOOTÉCNICO','EMPLOYMENT');
## TALLAS

INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('SIZE001','SMALL','SIZES');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('SIZE002','MEDIUN','SIZES');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('SIZE003','LARGE','SIZES');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('SIZE004','XLARGE','SIZES');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('SIZE006','2XL','SIZES');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('SIZE006','3XL','SIZES');

INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO01','O−','BLOODGRO');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO02','O+','BLOODGRO');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO03','A−','BLOODGRO');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO04','A+','BLOODGRO');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO05','B−','BLOODGRO');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO07','B+','BLOODGRO');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO08','AB−','BLOODGRO');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('BLOODGRO09','AB+','BLOODGRO');
------
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('MAT2018','MATRICULA','PRODUCTS');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('UNIFORME01','UNIFORMES ESTUDIANTES INFANTIL','PRODUCTS');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('UNIFORME02','UNIFORMES ESTUDIANTES CADETE','PRODUCTS');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('UNIFORME03','UNIFORMES ESTUDIANTES CADETE','PRODUCTS');
------
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('PAGO001','EFECTIVO','PAYMENTS');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('PAGO002','CHEQUE','PAYMENTS');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('PAGO003','ACH','PAYMENTS');

COMMIT;

SELECT * FROM SYSTEM_CODES WHERE SYSTEM_COD_GROUP='PAYMENTS';
SELECT * FROM SYSTEM_CODES WHERE SYSTEM_COD_GROUP='PRODUCTS';
/**
248
249
250
251
**/
UPDATE SYSTEM_CODES SET SYSTEM_COD_DESCRIPTION='UNIFORME ESTUDIANTE JUVENIL' WHERE IDSYSTEM_CODES=251;
INSERT INTO PRODUCTS (ID_PRODUCT,TYPE,DATE_REGISTRATION,EXPIRATION_DATE,USER_REGISTER,USER_EXPIRATION,UNIT_PRICE,TAX) VALUES(1,248,'2018-03-30','2999-12-31','JVEGA',' ', 50.0,0);
INSERT INTO PRODUCTS (ID_PRODUCT,TYPE,DATE_REGISTRATION,EXPIRATION_DATE,USER_REGISTER,USER_EXPIRATION,UNIT_PRICE,TAX) VALUES(2,249,'2018-03-30','2999-12-31','JVEGA',' ', 45.0,7);
INSERT INTO PRODUCTS (ID_PRODUCT,TYPE,DATE_REGISTRATION,EXPIRATION_DATE,USER_REGISTER,USER_EXPIRATION,UNIT_PRICE,TAX) VALUES(3,250,'2018-03-30','2999-12-31','JVEGA',' ', 50.0,7);
INSERT INTO PRODUCTS (ID_PRODUCT,TYPE,DATE_REGISTRATION,EXPIRATION_DATE,USER_REGISTER,USER_EXPIRATION,UNIT_PRICE,TAX) VALUES(4,251,'2018-03-30','2999-12-31','JVEGA',' ', 60.0,7);

INSERT INTO `dbbzk`.`system_parameters`
(`PARAMETER _ID`,
`DESCRIPTION`,
`DATE _CREATION`,
`EXPIRATION_DATE`,
`_KEY`,
`_VALUE`)
VALUES
(3,
'CANTIDAD DE DIAS PARA NOTIFICACION DE ACTIVIDADES',
'2018-04-08',
'2999-12-31',
'NOTIFICATION_ACTIVITIES',
'7');

COMMIT;
DESCRIBE system_parameters;

SELECT * FROM SYSTEM_PARAMETERS;

SELECT * FROM PRODUCTS;

SELECT * FROM STUDENT;

DESCRIBE PRODUCTS;

INSERT INTO `dbbzk`.`calendar_activities` (`activity_name`, `start_day_activity`, `end_ activity_day`, `activity_star_time`, `activity_end_time`, `type`, `publishing_social_networks`) VALUES ('ACTIVIDAD BZK002 ', '2018-04-16', '2018-04-16', '13', '17', '1', '0');
INSERT INTO `dbbzk`.`calendar_activities` (`activity_name`, `start_day_activity`, `end_ activity_day`, `activity_star_time`, `activity_end_time`, `type`, `publishing_social_networks`) VALUES ('ACTIVIDAD BZK003 ', '2018-04-19', '2018-04-19', '13', '17', '1', '0');
INSERT INTO `dbbzk`.`calendar_activities` (`activity_name`, `start_day_activity`, `end_ activity_day`, `activity_star_time`, `activity_end_time`, `type`, `publishing_social_networks`) VALUES ('COMPETENCIA DISTRITO PMA ', '2018-04-24', '2018-04-24', '8', '17', '2', '1');
INSERT INTO `dbbzk`.`calendar_activities` (`activity_name`, `start_day_activity`, `end_ activity_day`, `activity_star_time`, `activity_end_time`, `type`, `publishing_social_networks`) VALUES ('COMPETENCIA NACIONAL ', '2018-04-27', '2018-04-29', '8', '17', '2', '1');
COMMIT;

SELECT * FROM calendar_activities;