#select * from system_codes where system_cod_group like 'PRODUCTS%';
#Totales vs años
#select sum(total_payment) AS TOTAL_YEAR,DATE_FORMAT(PAYDAY,'%Y') AS _YEAR FROM PAYMENTS  GROUP BY _YEAR ORDER BY TOTAL_YEAR DESC;
#Desgloce de totales por tipo de pago
SELECT T._YEAR, 
SUM(IF((
SELECT SYSTEM_CODE 
FROM SYSTEM_CODES 
WHERE IDSYSTEM_CODES=T.TYPE_PAYMENT)='PAGO003',T.TOTAL_YEAR,0)) AS ACH,
SUM(IF((
SELECT SYSTEM_CODE 
FROM SYSTEM_CODES 
WHERE IDSYSTEM_CODES=T.TYPE_PAYMENT)='PAGO002',T.TOTAL_YEAR,0)) AS _CHECK,
SUM(IF((
SELECT SYSTEM_CODE 
FROM SYSTEM_CODES 
WHERE IDSYSTEM_CODES=T.TYPE_PAYMENT)='PAGO001',T.TOTAL_YEAR,0)) AS CASH

FROM (
SELECT SUM(P.total_payment) AS TOTAL_YEAR,
DATE_FORMAT(P.PAYDAY,'%Y%m') AS _YEAR,
P.type_payment AS TYPE_PAYMENT
FROM PAYMENTS  P
WHERE P.PAYDAY >='2017-01-01' AND 
      P.PAYDAY <='2018-07-26'
GROUP BY _YEAR,type_payment 
ORDER BY TOTAL_YEAR,TYPE_PAYMENT DESC
) T GROUP BY T._YEAR;