ALTER TABLE `STUDENT
` DROP FOREIGN KEY `FKSTUDENT
473429`;
ALTER TABLE ACCESS_PROFILE DROP FOREIGN KEY ACCES_PROFILE_VS_DASHBOARD;
ALTER TABLE ACCESS_PROFILE DROP FOREIGN KEY APP_PROFILE_VS_ACCESS;
ALTER TABLE ACCOUNT DROP FOREIGN KEY USER_VS_APP_PROFILE;
DROP TABLE IF EXISTS ACCESS_PROFILE;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS APP_PROFILE;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS SYSTEM_DASHBOARD;
DROP TABLE IF EXISTS TEACHER;

