# registros para borrar editar
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('1001','EDITAR','SYSACCION');
INSERT INTO SYSTEM_CODES (SYSTEM_CODE,SYSTEM_COD_DESCRIPTION,SYSTEM_COD_GROUP) VALUE('1002','ELIMINAR','SYSACCION');