
SELECT CONCAT(CONCAT(CONCAT(CONCAT(S.FIRST_NAME,','),S.SURNAME),','),S.SURNAME2) AS NAME,
S.ID_STUDENT, 
IFNULL(LAST_PAID_MONTHY,''),
IFNULL(ANNUITY_DATE,''),
LAST_PAID_MONTHY,
MONTH(_LAST_PAID_MONTHY),
MONTH(NOW()),
MONTH(_LAST_PAID_MONTHY) - MONTH(NOW()),


(YEAR(NOW()) - YEAR(_LAST_PAID_MONTHY)),


MONTH(S.DAY_OF_INCOME) - MONTH(NOW()),


IF((YEAR(NOW()) - YEAR(_LAST_PAID_MONTHY))=0,(IF((MONTH(NOW()) - MONTH(_LAST_PAID_MONTHY) )<=3,'SI','NO')),'NO') AS ACTIVE,



IF(MONTH(S.DAY_OF_INCOME) - MONTH(NOW())=0,'SI','NO') AS PENDING_PAYMENT_TUITIOM,

IF(DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) - YEAR(S.DAY_OF_INCOME))*365)),LAST_PAID_NO_FORMAT)>=-30 AND (DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) -YEAR(S.DAY_OF_INCOME))*365)),LAST_PAID_NO_FORMAT)<=0),'NO','SI')
 AS BOOLEAN_MONTHY_PAYMENT,
IF(
(DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) - YEAR(S.DAY_OF_INCOME))*365)),ANNUITY_DATE_NO_FORMAT)>=-335
 AND DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) - YEAR(S.DAY_OF_INCOME))*365)),ANNUITY_DATE_NO_FORMAT)<=0
 AND (
 (SELECT COUNT(D.ID_DETAIL_PAYMENTS)
FROM PAYMENTS P , DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE D.ID_STUDENT=S.ID_STUDENT
AND P.ID_PAYMENT=D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SUB_GROUP_DESCRIPTION ='MATRICULAS'
 ) >= (YEAR(NOW()) -YEAR(S.DAY_OF_INCOME)) )
 ) ,'NO','SI'
 ) AS BOOLEAN_ANNUITY_DATE,
S.DAY_OF_INCOME AS DAY_OF_INCOME
FROM STUDENT S LEFT OUTER JOIN (
SELECT DATE_FORMAT(MAX(P.PAYDAY), '%d/%m/%Y') AS  LAST_PAID_MONTHY,MAX(P.PAYDAY) as _LAST_PAID_MONTHY,D.ID_STUDENT,MAX(P.PAYDAY) AS LAST_PAID_NO_FORMAT 
FROM PAYMENTS P, DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE P.ID_PAYMENT = D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SUB_GROUP_DESCRIPTION ='CLASES'
GROUP BY D.ID_STUDENT
) T ON (S.ID_STUDENT =T.ID_STUDENT ),
STUDENT S2 LEFT OUTER JOIN  (SELECT DATE_FORMAT(MAX(P.PAYDAY), '%d/%m/%Y') AS ANNUITY_DATE,D.ID_STUDENT ,MAX(P.PAYDAY) AS ANNUITY_DATE_NO_FORMAT
FROM PAYMENTS P, DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE P.ID_PAYMENT = D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SUB_GROUP_DESCRIPTION = 'MATRICULAS'
GROUP BY D.ID_STUDENT) T2 ON (S2.ID_STUDENT =T2.ID_STUDENT )
WHERE S2.ID_STUDENT = S.ID_STUDENT
/*AND S.ID_STUDENT=217*/
ORDER BY NAME;
/*
SELECT DATE_FORMAT(MAX(P.PAYDAY), '%d/%m/%Y') AS  LAST_PAID_MONTHY,D.ID_STUDENT,MAX(P.PAYDAY) AS LAST_PAID_NO_FORMAT 
FROM PAYMENTS P, DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE P.ID_PAYMENT = D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SUB_GROUP_DESCRIPTION ='CLASES'
GROUP BY D.ID_STUDENT*/