/*SELECT * FROM DETAIL_PAYMENTS WHERE number_of_transfer = '10000130';
SELECT * FROM PAYMENTS  WHERE number_of_transfer = '10000130';

SELECT * FROM DETAIL_PAYMENTS WHERE ID_PAYMENT=513;
SELECT * FROM PAYMENTS  WHERE number_of_transfer = '10000001';
SELECT * FROM DETAIL_PAYMENTS WHERE ID_PAYMENT=513;
SELECT * FROM PRODUCTS WHERE ID_PRODUCT IN (2,5,6);

SELECT * FROM SYSTEM_CODES WHERE idsystem_codes IN (306,309,310);
*/
SELECT COUNT(1) FROM SYSTEM_CODES; /*117*/
