SELECT CONCAT(CONCAT(CONCAT(CONCAT(S.FIRST_NAME,','),S.SURNAME),','),S.SURNAME2) AS NAME,
S.ID_STUDENT, 
IFNULL(LAST_PAID_MONTHY,''),
IFNULL(ANNUITY_DATE,''),
(MONTH(LAST_PAID_MONTHY) - MONTH(NOW()) AS PENDIENTE_PAGO,
IF(MONTH(LAST_PAID_MONTHY) - MONTH(NOW())<=3,'SI','NO') AS ACTIVE,
IF(MONTH(S.DAY_OF_INCOME) - MONTH(NOW())=0,'SI','NO') AS PENDING_PAYMENT_TUITIOM,
IF(DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) - YEAR(S.DAY_OF_INCOME))*365)),LAST_PAID_NO_FORMAT)>=-30 AND (DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) -YEAR(S.DAY_OF_INCOME))*365)),LAST_PAID_NO_FORMAT)<=0),'NO','SI')
 AS BOOLEAN_MONTHY_PAYMENT,
IF(
(DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) - YEAR(S.DAY_OF_INCOME))*365)),ANNUITY_DATE_NO_FORMAT)>=-335
 AND DATEDIFF(ADDDATE(S.DAY_OF_INCOME,((YEAR(NOW()) - YEAR(S.DAY_OF_INCOME))*365)),ANNUITY_DATE_NO_FORMAT)<=0
 AND (
 (SELECT COUNT(D.ID_DETAIL_PAYMENTS)
FROM PAYMENTS P , DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE D.ID_STUDENT=S.ID_STUDENT
AND P.ID_PAYMENT=D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SYSTEM_CODE IN ('MAT2018','MATR00001') 
 ) >= (YEAR(NOW()) -YEAR(S.DAY_OF_INCOME)) )
 ) ,'NO','SI'
 ) AS BOOLEAN_ANNUITY_DATE,
S.DAY_OF_INCOME AS DAY_OF_INCOME
FROM STUDENT S LEFT OUTER JOIN (
SELECT DATE_FORMAT(MAX(P.PAYDAY), '%d/%m/%Y') AS  LAST_PAID_MONTHY,D.ID_STUDENT,MAX(P.PAYDAY) AS LAST_PAID_NO_FORMAT 
FROM PAYMENTS P, DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE P.ID_PAYMENT = D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SYSTEM_CODE IN ('CLAS00001','CLAS00004','CLAS00005')
GROUP BY D.ID_STUDENT
) T ON (S.ID_STUDENT =T.ID_STUDENT ),
STUDENT S2 LEFT OUTER JOIN  (SELECT DATE_FORMAT(MAX(P.PAYDAY), '%d/%m/%Y') AS ANNUITY_DATE,D.ID_STUDENT ,MAX(P.PAYDAY) AS ANNUITY_DATE_NO_FORMAT
FROM PAYMENTS P, DETAIL_PAYMENTS D,SYSTEM_CODES C,PRODUCTS PROD
WHERE P.ID_PAYMENT = D.ID_PAYMENT
AND D.ID_PRODUCT = PROD.ID_PRODUCT
AND PROD.TYPE = C.IDSYSTEM_CODES 
AND C.SYSTEM_CODE IN ('MAT2018','MATR00001')
GROUP BY D.ID_STUDENT) T2 ON (S2.ID_STUDENT =T2.ID_STUDENT )
WHERE S2.ID_STUDENT = S.ID_STUDENT
ORDER BY NAME