-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.2.12-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             9.4.0.5125
-- --------------------------------------------------------
ALTER TABLE `system_parameters`
	ALTER `DESCRIPTION` DROP DEFAULT;
ALTER TABLE `system_parameters`
	CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(80) NOT NULL COLLATE 'latin1_bin' AFTER `_VALUE`,
	DROP COLUMN `PARAMETER_ID`;
ALTER TABLE `system_parameters`
	ALTER `PARAMETER _ID` DROP DEFAULT;
ALTER TABLE `system_parameters`
	CHANGE COLUMN `PARAMETER _ID` `PARAMETER_ID` INT(11) NOT NULL FIRST;
	
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando datos para la tabla dbbzk.system_parameters: ~5 rows (aproximadamente)
/*!40000 ALTER TABLE `system_parameters` DISABLE KEYS */;
DELETE FROM system_parameters WHERE PARAMETER_ID>0;
INSERT INTO `system_parameters` (`PARAMETER_ID`, `DESCRIPTION`, `DATE_CREATION`, `EXPIRATION_DATE`, `_KEY`, `_VALUE`) VALUES
	(1, 'CANTIDAD DE DIAS PARA NOTIFICACION DE INSCRIPCIONES ', '2018-03-29', '2999-12-31', 'DAYS_REG_NOTIFICATION', '7'),
	(2, 'CANTIDAD DE DIAS PARA NOTIFICACION DE PAGOS', '2018-03-30', '2999-12-31', 'PAYMENT_NOTIFICATION', '3'),
	(3, 'CANTIDAD DE DIAS PARA NOTIFICACION DE ACTIVIDADES', '2018-04-08', '2999-12-31', 'NOTIFICATION_ACTIVITIES', '7'),
	(4, 'BORRAR LOS ARCHIVOS PDF EXISTENTES', '2018-07-19', '2999-12-31', 'DELETE_PDF', '1'),
	(5, 'PARAMETRO DE AÑOS ATRAS PARA LA GRAFICA ', '2018-07-26', '2999-12-31', 'YEAR_AGO', '2');
/*!40000 ALTER TABLE `system_parameters` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
COMMIT;
